# For more see: http://jekyllrb.com/docs/permalinks/
permalink: date

exclude: [".ruby-version", ".ruby-gemset", "README.md", "Rakefile"]
pygments: true
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "autolink", "strikethrough", "superscript"]

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title: Michel Billard
tagline: "Web Enthusiast / Technology Geek / Gamer"
author:
  name: Michel Billard
  bio:
    This is my bio
    that spans multiple lines.
  location: Montreal, QC, Canada
  occupation: Web developer
  # email: blah@email.test
  # blogger:
  # dribble:
  facebook: billard.michel
  github: mbillard
  google_plus: +MichelBillard
  # instagram:
  linkedin: mbillard
  steam: gogosse
  twitter: gogosse
  # wordpress:

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url: http://www.mbillard.com

# Theme specific variables, switches, etc.
#
theme:
  minime:
    social_links: ['linkedin', 'twitter', 'facebook', 'google_plus', 'blogger', 'dribble', 'github', 'instagram', 'steam', 'wordpress']
    # Each link will be displayed in the order listed here
    # Format:
    #
    #  name:
    #  description:
    #  url:
    #  image:
    #
    links:
      - name: Out of Scope
        description: Blog about software development related topics
        url: http://www.outofscope.com
        # image:
      - name: Survvit
        description: Simple one-question survey creator
        url: http://www.survvit.com
        # image:
      - name: VarageSale
        description: A virtual garage sale site. We're building this at Codified.
        url: http://www.varagesale.com
        # image:
    # header:
    #   avatar_image_path: images/michel-billard-6.jpg
    #   avatar_small_image_path: images/michel-billard-6.jpg
    #   links: ['twitter', 'facebook', 'google_plus', 'linkedin']

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#
analytics:
  provider: google
  google:
      tracking_id: 'UA-1804335-1'
