# For more see: http://jekyllrb.com/docs/permalinks/
permalink: date

exclude: [".ruby-version", ".ruby-gemset", "README.md", "Rakefile"]
highlighter: rouge
markdown: kramdown

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title: // Michel Billard
tagline: "Web Enthusiast / Technology Geek / Gamer"
author:
  name: Michel Billard
  bio:
    "I'm a web developer with a passion for building great products with good user experiences and interaction
    design. I favor a very pragmatic approach when it comes to solving engineering
    problems."
  # location: Montreal, QC, Canada
  # occupation: Web developer
  # email: blah@email.test
  # blogger:
  # dribble:
  facebook: billard.michel
  github: mbillard
  # google_plus: +MichelBillard
  # instagram:
  linkedin: mbillard
  stackoverflow: 810/mbillard
  # steam: gogosse
  twitter: crossbrowser
  # wordpress:

social_links: ['blogger', 'dribble', 'facebook', 'github', 'google_plus', 'instagram', 'linkedin', 'stackoverflow', 'steam', 'twitter', 'wordpress']

# Each link will be displayed in the order listed here
# Format:
#
#  name:
#  description:
#  url:
#
links:
  - name: Out of Scope
    description: Blog about software development related topics
    url: http://www.outofscope.com
  - name: Aha!
    description: "The world's #1 product roadmap software"
    url: https://www.aha.io
  - name: Grid Framework
    description: A highly customizable responsive grid framework.
    url: http://mbillard.com/grid-framework/
  - name: Survvit
    description: Simple one-question survey creator
    url: http://www.survvit.com
  - name: "Gars d'Intérieur"
    description: "(French) Chaîne YouTube où je fais découvrir des jeux de société."
    url: https://www.youtube.com/channel/UCi7YUS4F8na2z8G9nl0H0WA
  - name: Ville Reine
    description: "(French) Blogue de 2 montréalais exilés à Toronto."
    url: http://www.villereine.ca

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url: http://www.mbillard.com

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#
analytics:
  provider: google
  google:
      tracking_id: 'UA-1804335-1'
