source "http://rubygems.org"

# gem 'rake', '~> 0.9'
gem 'jekyll', '~> 1.4.2'
gem 'guard-jekyll'
gem 'guard-compass'
# gem 'rdiscount', '~> 2.0.7'
# gem 'pygments.rb', '~> 0.3.4'
# gem 'RedCloth', '~> 4.2.9'
gem 'redcarpet', '~> 2.3.0'
# gem 'jekyll-asset-pipeline', '~> 0.1.6'
gem 'compass', '~> 0.12.2'
# gem 'sass-globbing', '~> 1.0.0'
gem 'sass', '~> 3.2.13'
gem 'foreman'
# gem 'rubypants', '~> 0.2.0'
# gem 'rb-fsevent', '~> 0.9'
# gem 'stringex', '~> 1.4.0'
# gem 'liquid', '~> 2.3.0'

# gem 'sinatra', '~> 1.4.2'
